from enum import Enum	

class GameStates(Enum):
    PLAYERS_TURN = 1
    ENEMY_TURN = 2
    PLAYER_DEAD = 3
    SHOW_INVENTORY = 4
    DROP_INVENTORY = 5
    TARGETING = 6
    LEVEL_UP = 7
    CHARACTER_MENU = 8
    PRIMARY_STATS_SCREEN = 9
    COMBAT_STATS_SCREEN = 10
    FEATS_MENU = 11
    STRENGTH_FEATS = 12
    INSTINCT_FEATS = 13
    COORDINATION_FEATS = 14
    VITALITY_FEATS = 15
    ARCANA_FEATS = 16
    IMPROVISATION_FEATS = 17
    WISDOM_FEATS = 18
    FINESSE_FEATS = 19
    CHARISMA_FEATS = 20
    DEVOTION_FEATS = 21