import pygame as py
from screens.frozen_surface import FrozenSurface
from ECS.image_bundle import ImageBundle

TITLE_SCREEN_BG = py.image.load('images\\background\\main_menu.png')
TITLE_MENU_BG = py.image.load('images\\GUI\\main_menu.png')
TITLE_MENU_BUTTON = py.image.load('images\\GUI\\mm_button.png')

MESSAGE_BG = py.image.load('images\\GUI\\message_bg.png')
ENCOUNTER_MESSAGE_BG = py.image.load('images\\GUI\\encounter\\message_bg.png')
ENCOUNTER_MENU = py.image.load('images\\GUI\\menus\\encounter_menu.png')
ENCOUNTER_BUTTON = py.image.load('images\\GUI\\menus\\option_button.png')
DIALOGUE_MENU = py.image.load('images\\GUI\\dialogue_menu.png')
SHOP_MENU = py.image.load('images\\GUI\\shop_menu.png')
LEVELUP_MENU = py.image.load('images\\GUI\\levelup_menu.png')

INVENTORY_BG = py.image.load('images\\GUI\\inventory\\inven_bg.png')
EQUIPMENT_BG = py.image.load('images\\GUI\\inventory\\equipment_bg.png')
INVENTORY_OPTIONS = [py.image.load('images\\GUI\\inventory\\miscellaneous.png'),
                     py.image.load('images\\GUI\\inventory\\weapons.png'),
                     py.image.load('images\\GUI\\inventory\\armor.png'),
                     py.image.load('images\\GUI\\inventory\\accessories.png'),
                     py.image.load('images\\GUI\\inventory\\satchel.png'),
                     py.image.load('images\\GUI\\inventory\\materials.png'),
                     py.image.load('images\\GUI\\inventory\\plot.png')]

LIFE_BACKDROP = py.image.load('images\\GUI\\life\\life_backdrop.png')
MINI_MAP = py.image.load('images\\GUI\\life\\minimap.png')
CLOCK = py.image.load('images\\GUI\\life\\clock.png')
UPCOMING_EVENTS = py.image.load('images\\GUI\\life\\upcoming_events.png')
TURN_ORDER_QUEUE = py.image.load('images\\GUI\\encounter\\turn_order_queue.png')

GOLD = py.image.load('images\\GUI\\menus\\silver.png')
SILVER = py.image.load('images\\GUI\\menus\\silver.png')
COPPER = py.image.load('images\\GUI\\menus\\copper.png')

JOURNAL_OBJS = {
    'bg': py.image.load('images\\GUI\\journal\\journal_bg.png'),
    'icon0': py.image.load('images\\GUI\\journal\\current.png'),
    'text0': py.image.load('images\\GUI\\journal\\current_text.png'),
    'icon1': py.image.load('images\\GUI\\journal\\completed.png'),
    'text1': py.image.load('images\\GUI\\journal\\completed_text.png'),
    'icon2': py.image.load('images\\GUI\\journal\\codex.png'),
    'text2': py.image.load('images\\GUI\\journal\\codex_text.png'),
    'icon3': py.image.load('images\\GUI\\journal\\history.png'),
    'text3': py.image.load('images\\GUI\\journal\\history_text.png'),
    'quest_holder': py.image.load('images\\GUI\\journal\\quest_holder.png'),
}

LOOT_BG = py.image.load('images\\GUI\\looting\\loot_bg.png')
LOOT_BANNER = py.image.load('images\\GUI\\looting\\loot_banner.png')

CALENDAR_BG = py.image.load('images\\GUI\\life\\calendar.png')
CALENDAR_CIRCLE = py.image.load('images\\GUI\\life\\calendar_circle.png')

INDICATOR_H = py.image.load('images\\GUI\\menus\\indicator_h.png')
INDICATOR_V = py.image.load('images\\GUI\\menus\\indicator_v.png')

STAIRS_DOWN = ImageBundle(py.image.load('images\\entities\\transitions\\stairsdown.png'))
STAIRS_UP = ImageBundle(py.image.load('images\\entities\\transitions\\stairsup.png'))

ALPHA = py.image.load('images\\alpha.png')
BUNDLE_ALPHA = ImageBundle(ALPHA)

BUNDLE_HERO = ImageBundle(py.image.load('images\\entities\\combatants\\hero\\sprite.png'),
                          py.image.load('images\\entities\\combatants\\hero\\portrait.png'),
                          py.image.load('images\\entities\\combatants\\hero\\port_mini.png'),
                          py.image.load('images\\entities\\combatants\\hero\\actor.png'))

BUNDLE_SAMWISE = ImageBundle(py.image.load('images\\entities\\noncombatants\\samwise\\sprite.png'),
                             py.image.load('images\\entities\\noncombatants\\samwise\\portrait.png'),
                             py.image.load('images\\entities\\noncombatants\\samwise\\port_mini.png'))

BUNDLE_STICK = ImageBundle(py.image.load('images\\entities\\items\\equippables\\weapons\\stick\\sprite.png'),
                           py.image.load('images\\entities\\items\\equippables\\weapons\\stick\\portrait.png'),
                           py.image.load('images\\entities\\items\\equippables\\weapons\\stick\\port_mini.png'))

BUNDLE_WEAPONS = {
    'staff': ImageBundle(py.image.load('images\\entities\\items\\equippables\\weapons\\staff\\sprite.png')),
    'dagger': ImageBundle(py.image.load('images\\entities\\items\\equippables\\weapons\\dagger\\sprite.png')),
    'shield': ImageBundle(py.image.load('images\\entities\\items\\equippables\\weapons\\shield\\sprite.png')),
    'longsword': ImageBundle(py.image.load('images\\entities\\items\\equippables\\weapons\\longsword\\sprite.png'),
                             py.image.load('images\\entities\\items\\equippables\\weapons\\longsword\\portrait.png')),
}

BUNDLE_POTION = ImageBundle(py.image.load('images\\entities\\items\\useables\\potion\\sprite.png'),
                            py.image.load('images\\entities\\items\\useables\\potion\\portrait.png'),
                            py.image.load('images\\entities\\items\\useables\\potion\\port_mini.png'))
SCROLL = py.image.load('images\\entities\\items\\useables\\scroll\\sprite.png')

BUNDLE_MOBS = {
    'rat': ImageBundle(actor=py.image.load('images\\entities\\combatants\\rat\\actor.png')),
    'bat': ImageBundle(actor=py.image.load('images\\entities\\combatants\\bat\\actor.png')),
    'bear': ImageBundle(actor=py.image.load('images\\entities\\combatants\\bear\\actor.png')),
    'goblin': ImageBundle(actor=py.image.load('images\\entities\\combatants\\goblin\\actor.png')),
    'kobold': ImageBundle(actor=py.image.load('images\\entities\\combatants\\kobold\\actor.png')),
    'raccoon': ImageBundle(actor=py.image.load('images\\entities\\combatants\\raccoon\\actor.png')),
    'salamander': ImageBundle(actor=py.image.load('images\\entities\\combatants\\salamander\\actor.png')),
    'snail': ImageBundle(actor=py.image.load('images\\entities\\combatants\\snail\\actor.png')),
    'shrimp': ImageBundle(actor=py.image.load('images\\entities\\combatants\\shrimp\\actor.png')),
    'spider': ImageBundle(actor=py.image.load('images\\entities\\combatants\\spider\\actor.png')),
}

CHARACTER_SCREEN = {
    'bg': py.image.load('images\\GUI\\character_sheet\\char_sheet.png'),
    'level': py.image.load('images\\GUI\\character_sheet\\level_icon.png'),
    'age': py.image.load('images\\GUI\\character_sheet\\age_icon.png'),
    'power': py.image.load('images\\GUI\\character_sheet\\power.png'),
    'resistance': py.image.load('images\\GUI\\character_sheet\\resistance.png'),
    'slash': py.image.load('images\\GUI\\character_sheet\\slash.png'),
    'pierce': py.image.load('images\\GUI\\character_sheet\\pierce.png'),
    'blunt': py.image.load('images\\GUI\\character_sheet\\blunt.png'),
    'heat': py.image.load('images\\GUI\\character_sheet\\heat.png'),
    'cold': py.image.load('images\\GUI\\character_sheet\\cold.png'),
    'acid': py.image.load('images\\GUI\\character_sheet\\acid.png'),
    'current': py.image.load('images\\GUI\\character_sheet\\current.png'),
    'aether': py.image.load('images\\GUI\\character_sheet\\aether.png'),
    'accuracy': py.image.load('images\\GUI\\character_sheet\\accuracy.png'),
    'dodge': py.image.load('images\\GUI\\character_sheet\\dodge.png'),
    'initiative': py.image.load('images\\GUI\\character_sheet\\initiative.png'),
    'speed': py.image.load('images\\GUI\\character_sheet\\speed.png'),
    'teamwork': py.image.load('images\\GUI\\character_sheet\\teamwork.png'),
    'leadership': py.image.load('images\\GUI\\character_sheet\\leadership.png'),
    'presence': py.image.load('images\\GUI\\character_sheet\\presence.png'),
    'reflex': py.image.load('images\\GUI\\character_sheet\\reflex.png'),
    'balance': py.image.load('images\\GUI\\character_sheet\\balance.png'),
    'breath': py.image.load('images\\GUI\\character_sheet\\breath.png'),
    'grapple': py.image.load('images\\GUI\\character_sheet\\grapple.png'),
    'stun': py.image.load('images\\GUI\\character_sheet\\stun.png'),
    'panic': py.image.load('images\\GUI\\character_sheet\\panic.png'),
    'apathy': py.image.load('images\\GUI\\character_sheet\\apathy.png'),
    'pain': py.image.load('images\\GUI\\character_sheet\\pain.png'),
    'bewitch': py.image.load('images\\GUI\\character_sheet\\bewitch.png'),
    'enrage': py.image.load('images\\GUI\\character_sheet\\enrage.png'),
    'illness': py.image.load('images\\GUI\\character_sheet\\illness.png'),
    'tenacity': py.image.load('images\\GUI\\character_sheet\\tenacity.png'),
    'pressure': py.image.load('images\\GUI\\character_sheet\\pressure.png'),
    'bleed': py.image.load('images\\GUI\\character_sheet\\bleed.png'),
    'injury': py.image.load('images\\GUI\\character_sheet\\injury.png'),
    'xp_bar': py.image.load('images\\GUI\\character_sheet\\xp_bar.png'),
    'xp0': py.image.load('images\\GUI\\character_sheet\\xp0.png'),
    'xp1': py.image.load('images\\GUI\\character_sheet\\xp1.png'),
    'xp2': py.image.load('images\\GUI\\character_sheet\\xp2.png'),
    'xp3': py.image.load('images\\GUI\\character_sheet\\xp3.png'),
    'xp4': py.image.load('images\\GUI\\character_sheet\\xp4.png'),
    'human': py.image.load('images\\GUI\\character_sheet\\human_icon.png'),
    'male': py.image.load('images\\GUI\\character_sheet\\male_icon.png'),
    'female': py.image.load('images\\GUI\\character_sheet\\female_icon.png'),
}
RESOURCE_HUD_BASE = py.image.load('images\\GUI\\life\\resources_hud\\base_layer.png')
RESOURCE_HUD_OVERLAY = py.image.load('images\\GUI\\life\\resources_hud\\portrait_overlay.png')
HP = py.image.load('images\\GUI\\life\\resources_hud\\hp.png')
MP = py.image.load('images\\GUI\\life\\resources_hud\\mp.png')
TP = py.image.load('images\\GUI\\life\\resources_hud\\tp.png')
VP = py.image.load('images\\GUI\\life\\resources_hud\\vp.png')

PARTY_SETTINGS_FRAME = py.image.load('images\\GUI\\life\\party_settings_frame.png')

RESOURCE_HUD = {
    'frame': py.image.load('images\\GUI\\resources_hud\\portrait_mini_frame.png'),
    'resource_bar': py.image.load('images\\GUI\\resources_hud\\resource_bar.png'),
    'HP': py.image.load('images\\GUI\\resources_hud\\HP.png'),
    'MP': py.image.load('images\\GUI\\resources_hud\\MP.png'),
    'TP': py.image.load('images\\GUI\\resources_hud\\TP.png'),
    'VP': py.image.load('images\\GUI\\resources_hud\\VP.png'),
    'HPleft0': py.image.load('images\\GUI\\resources_hud\\real_hp\\left0.png'),
    'HPleft1': py.image.load('images\\GUI\\resources_hud\\real_hp\\left1.png'),
    'HPmid': py.image.load('images\\GUI\\resources_hud\\real_hp\\mid.png'),
    'HPright0': py.image.load('images\\GUI\\resources_hud\\real_hp\\right0.png'),
    'HPright1': py.image.load('images\\GUI\\resources_hud\\real_hp\\right1.png'),
    'MPleft0': py.image.load('images\\GUI\\resources_hud\\real_mp\\left0.png'),
    'MPleft1': py.image.load('images\\GUI\\resources_hud\\real_mp\\left1.png'),
    'MPmid': py.image.load('images\\GUI\\resources_hud\\real_mp\\mid.png'),
    'MPright0': py.image.load('images\\GUI\\resources_hud\\real_mp\\right0.png'),
    'MPright1': py.image.load('images\\GUI\\resources_hud\\real_mp\\right1.png'),
    'TPleft0': py.image.load('images\\GUI\\resources_hud\\real_tp\\left0.png'),
    'TPleft1': py.image.load('images\\GUI\\resources_hud\\real_tp\\left1.png'),
    'TPmid': py.image.load('images\\GUI\\resources_hud\\real_tp\\mid.png'),
    'TPright0': py.image.load('images\\GUI\\resources_hud\\real_tp\\right0.png'),
    'TPright1': py.image.load('images\\GUI\\resources_hud\\real_tp\\right1.png'),
    'VPleft0': py.image.load('images\\GUI\\resources_hud\\real_vp\\left0.png'),
    'VPleft1': py.image.load('images\\GUI\\resources_hud\\real_vp\\left1.png'),
    'VPmid': py.image.load('images\\GUI\\resources_hud\\real_vp\\mid.png'),
    'VPright0': py.image.load('images\\GUI\\resources_hud\\real_vp\\right0.png'),
    'VPright1': py.image.load('images\\GUI\\resources_hud\\real_vp\\right1.png'),
}
BACKGROUNDS = {
    'deep': py.image.load('images\\background\\deep.png'),
    'desert': py.image.load('images\\background\\desert.png'),
    'forest': py.image.load('images\\background\\forest.png'),
    'plains': py.image.load('images\\background\\plains.png'),
    'savannah': py.image.load('images\\background\\savannah.png'),
    'shallow': py.image.load('images\\background\\shallow.png'),
    'snow': py.image.load('images\\background\\snow.png'),
    'taiga': py.image.load('images\\background\\taiga.png'),
    'temprain': py.image.load('images\\background\\temprain.png'),
    'tropicrain': py.image.load('images\\background\\tropicrain.png'),
    'tundra': py.image.load('images\\background\\tundra.png'),
    'cave': py.image.load('images\\background\\cave.png'),
}

MINIMAP = {
    'deep': py.image.load('images\\tiles\\overworld\\mini_map\\deep.png'),
    'desert': py.image.load('images\\tiles\\overworld\\mini_map\\desert.png'),
    'forest': py.image.load('images\\tiles\\overworld\\mini_map\\forest.png'),
    'plains': py.image.load('images\\tiles\\overworld\\mini_map\\plains.png'),
    'savannah': py.image.load('images\\tiles\\overworld\\mini_map\\savannah.png'),
    'shallow': py.image.load('images\\tiles\\overworld\\mini_map\\shallow.png'),
    'snow': py.image.load('images\\tiles\\overworld\\mini_map\\snow.png'),
    'taiga': py.image.load('images\\tiles\\overworld\\mini_map\\taiga.png'),
    'temprain': py.image.load('images\\tiles\\overworld\\mini_map\\temprain.png'),
    'tropicrain': py.image.load('images\\tiles\\overworld\\mini_map\\tropicrain.png'),
    'tundra': py.image.load('images\\tiles\\overworld\\mini_map\\tundra.png')

}

LIGHT_DEEP = [py.image.load('images\\tiles\\overworld\\deep\\light_deep0.png'),
              py.image.load('images\\tiles\\overworld\\deep\\light_deep1.png'),
              py.image.load('images\\tiles\\overworld\\deep\\light_deep2.png'),
              py.image.load('images\\tiles\\overworld\\deep\\light_deep3.png'),
              py.image.load('images\\tiles\\overworld\\deep\\light_deep4.png'),
              py.image.load('images\\tiles\\overworld\\deep\\light_deep5.png'),
              py.image.load('images\\tiles\\overworld\\deep\\light_deep6.png'),
              py.image.load('images\\tiles\\overworld\\deep\\light_deep7.png'),
              py.image.load('images\\tiles\\overworld\\deep\\light_deep8.png')]
DARK_DEEP = [py.image.load('images\\tiles\\overworld\\deep\\dark_deep0.png'),
             py.image.load('images\\tiles\\overworld\\deep\\dark_deep1.png'),
             py.image.load('images\\tiles\\overworld\\deep\\dark_deep2.png'),
             py.image.load('images\\tiles\\overworld\\deep\\dark_deep3.png'),
             py.image.load('images\\tiles\\overworld\\deep\\dark_deep4.png'),
             py.image.load('images\\tiles\\overworld\\deep\\dark_deep5.png'),
             py.image.load('images\\tiles\\overworld\\deep\\dark_deep6.png'),
             py.image.load('images\\tiles\\overworld\\deep\\dark_deep7.png'),
             py.image.load('images\\tiles\\overworld\\deep\\dark_deep8.png')]
LIGHT_DESERT = [py.image.load('images\\tiles\\overworld\\desert\\light_desert0.png'),
                py.image.load('images\\tiles\\overworld\\desert\\light_desert1.png'),
                py.image.load('images\\tiles\\overworld\\desert\\light_desert2.png'),
                py.image.load('images\\tiles\\overworld\\desert\\light_desert3.png'),
                py.image.load('images\\tiles\\overworld\\desert\\light_desert4.png'),
                py.image.load('images\\tiles\\overworld\\desert\\light_desert5.png'),
                py.image.load('images\\tiles\\overworld\\desert\\light_desert6.png'),
                py.image.load('images\\tiles\\overworld\\desert\\light_desert7.png'),
                py.image.load('images\\tiles\\overworld\\desert\\light_desert8.png')]
DARK_DESERT = [py.image.load('images\\tiles\\overworld\\desert\\dark_desert0.png'),
               py.image.load('images\\tiles\\overworld\\desert\\dark_desert1.png'),
               py.image.load('images\\tiles\\overworld\\desert\\dark_desert2.png'),
               py.image.load('images\\tiles\\overworld\\desert\\dark_desert3.png'),
               py.image.load('images\\tiles\\overworld\\desert\\dark_desert4.png'),
               py.image.load('images\\tiles\\overworld\\desert\\dark_desert5.png'),
               py.image.load('images\\tiles\\overworld\\desert\\dark_desert6.png'),
               py.image.load('images\\tiles\\overworld\\desert\\dark_desert7.png'),
               py.image.load('images\\tiles\\overworld\\desert\\dark_desert8.png')]
LIGHT_FOREST = [py.image.load('images\\tiles\\overworld\\forest\\light_forest0.png'),
                py.image.load('images\\tiles\\overworld\\forest\\light_forest1.png'),
                py.image.load('images\\tiles\\overworld\\forest\\light_forest2.png'),
                py.image.load('images\\tiles\\overworld\\forest\\light_forest3.png'),
                py.image.load('images\\tiles\\overworld\\forest\\light_forest4.png'),
                py.image.load('images\\tiles\\overworld\\forest\\light_forest5.png'),
                py.image.load('images\\tiles\\overworld\\forest\\light_forest6.png'),
                py.image.load('images\\tiles\\overworld\\forest\\light_forest7.png'),
                py.image.load('images\\tiles\\overworld\\forest\\light_forest8.png')]
DARK_FOREST = [py.image.load('images\\tiles\\overworld\\forest\\dark_forest0.png'),
               py.image.load('images\\tiles\\overworld\\forest\\dark_forest1.png'),
               py.image.load('images\\tiles\\overworld\\forest\\dark_forest2.png'),
               py.image.load('images\\tiles\\overworld\\forest\\dark_forest3.png'),
               py.image.load('images\\tiles\\overworld\\forest\\dark_forest4.png'),
               py.image.load('images\\tiles\\overworld\\forest\\dark_forest5.png'),
               py.image.load('images\\tiles\\overworld\\forest\\dark_forest6.png'),
               py.image.load('images\\tiles\\overworld\\forest\\dark_forest7.png'),
               py.image.load('images\\tiles\\overworld\\forest\\dark_forest8.png')]
LIGHT_PLAINS = [py.image.load('images\\tiles\\overworld\\plains\\light_plains0.png'),
                py.image.load('images\\tiles\\overworld\\plains\\light_plains1.png'),
                py.image.load('images\\tiles\\overworld\\plains\\light_plains2.png'),
                py.image.load('images\\tiles\\overworld\\plains\\light_plains3.png'),
                py.image.load('images\\tiles\\overworld\\plains\\light_plains4.png'),
                py.image.load('images\\tiles\\overworld\\plains\\light_plains5.png'),
                py.image.load('images\\tiles\\overworld\\plains\\light_plains6.png'),
                py.image.load('images\\tiles\\overworld\\plains\\light_plains7.png'),
                py.image.load('images\\tiles\\overworld\\plains\\light_plains8.png')]
DARK_PLAINS = [py.image.load('images\\tiles\\overworld\\plains\\dark_plains0.png'),
               py.image.load('images\\tiles\\overworld\\plains\\dark_plains1.png'),
               py.image.load('images\\tiles\\overworld\\plains\\dark_plains2.png'),
               py.image.load('images\\tiles\\overworld\\plains\\dark_plains3.png'),
               py.image.load('images\\tiles\\overworld\\plains\\dark_plains4.png'),
               py.image.load('images\\tiles\\overworld\\plains\\dark_plains5.png'),
               py.image.load('images\\tiles\\overworld\\plains\\dark_plains6.png'),
               py.image.load('images\\tiles\\overworld\\plains\\dark_plains7.png'),
               py.image.load('images\\tiles\\overworld\\plains\\dark_plains8.png')]
LIGHT_SAVANNAH = [py.image.load('images\\tiles\\overworld\\savannah\\light_savannah0.png'),
                  py.image.load('images\\tiles\\overworld\\savannah\\light_savannah1.png'),
                  py.image.load('images\\tiles\\overworld\\savannah\\light_savannah2.png'),
                  py.image.load('images\\tiles\\overworld\\savannah\\light_savannah3.png'),
                  py.image.load('images\\tiles\\overworld\\savannah\\light_savannah4.png'),
                  py.image.load('images\\tiles\\overworld\\savannah\\light_savannah5.png'),
                  py.image.load('images\\tiles\\overworld\\savannah\\light_savannah6.png'),
                  py.image.load('images\\tiles\\overworld\\savannah\\light_savannah7.png'),
                  py.image.load('images\\tiles\\overworld\\savannah\\light_savannah8.png'), ]
DARK_SAVANNAH = [py.image.load('images\\tiles\\overworld\\savannah\\dark_savannah0.png'),
                 py.image.load('images\\tiles\\overworld\\savannah\\dark_savannah1.png'),
                 py.image.load('images\\tiles\\overworld\\savannah\\dark_savannah2.png'),
                 py.image.load('images\\tiles\\overworld\\savannah\\dark_savannah3.png'),
                 py.image.load('images\\tiles\\overworld\\savannah\\dark_savannah4.png'),
                 py.image.load('images\\tiles\\overworld\\savannah\\dark_savannah5.png'),
                 py.image.load('images\\tiles\\overworld\\savannah\\dark_savannah6.png'),
                 py.image.load('images\\tiles\\overworld\\savannah\\dark_savannah7.png'),
                 py.image.load('images\\tiles\\overworld\\savannah\\dark_savannah8.png'), ]
LIGHT_SHALLOW = [py.image.load('images\\tiles\\overworld\\shallow\\light_shallow0.png'),
                 py.image.load('images\\tiles\\overworld\\shallow\\light_shallow1.png'),
                 py.image.load('images\\tiles\\overworld\\shallow\\light_shallow2.png'),
                 py.image.load('images\\tiles\\overworld\\shallow\\light_shallow3.png'),
                 py.image.load('images\\tiles\\overworld\\shallow\\light_shallow4.png'),
                 py.image.load('images\\tiles\\overworld\\shallow\\light_shallow5.png'),
                 py.image.load('images\\tiles\\overworld\\shallow\\light_shallow6.png'),
                 py.image.load('images\\tiles\\overworld\\shallow\\light_shallow7.png'),
                 py.image.load('images\\tiles\\overworld\\shallow\\light_shallow8.png')]
DARK_SHALLOW = [py.image.load('images\\tiles\\overworld\\shallow\\dark_shallow0.png'),
                py.image.load('images\\tiles\\overworld\\shallow\\dark_shallow1.png'),
                py.image.load('images\\tiles\\overworld\\shallow\\dark_shallow2.png'),
                py.image.load('images\\tiles\\overworld\\shallow\\dark_shallow3.png'),
                py.image.load('images\\tiles\\overworld\\shallow\\dark_shallow4.png'),
                py.image.load('images\\tiles\\overworld\\shallow\\dark_shallow5.png'),
                py.image.load('images\\tiles\\overworld\\shallow\\dark_shallow6.png'),
                py.image.load('images\\tiles\\overworld\\shallow\\dark_shallow7.png'),
                py.image.load('images\\tiles\\overworld\\shallow\\dark_shallow8.png')]
LIGHT_SNOW = [py.image.load('images\\tiles\\overworld\\snow\\light_snow0.png'),
              py.image.load('images\\tiles\\overworld\\snow\\light_snow1.png'),
              py.image.load('images\\tiles\\overworld\\snow\\light_snow2.png'),
              py.image.load('images\\tiles\\overworld\\snow\\light_snow3.png'),
              py.image.load('images\\tiles\\overworld\\snow\\light_snow4.png'),
              py.image.load('images\\tiles\\overworld\\snow\\light_snow5.png'),
              py.image.load('images\\tiles\\overworld\\snow\\light_snow6.png'),
              py.image.load('images\\tiles\\overworld\\snow\\light_snow7.png'),
              py.image.load('images\\tiles\\overworld\\snow\\light_snow8.png')]
DARK_SNOW = [py.image.load('images\\tiles\\overworld\\snow\\dark_snow0.png'),
             py.image.load('images\\tiles\\overworld\\snow\\dark_snow1.png'),
             py.image.load('images\\tiles\\overworld\\snow\\dark_snow2.png'),
             py.image.load('images\\tiles\\overworld\\snow\\dark_snow3.png'),
             py.image.load('images\\tiles\\overworld\\snow\\dark_snow4.png'),
             py.image.load('images\\tiles\\overworld\\snow\\dark_snow5.png'),
             py.image.load('images\\tiles\\overworld\\snow\\dark_snow6.png'),
             py.image.load('images\\tiles\\overworld\\snow\\dark_snow7.png'),
             py.image.load('images\\tiles\\overworld\\snow\\dark_snow8.png')]
LIGHT_TAIGA = [py.image.load('images\\tiles\\overworld\\taiga\\light_taiga0.png'),
               py.image.load('images\\tiles\\overworld\\taiga\\light_taiga1.png'),
               py.image.load('images\\tiles\\overworld\\taiga\\light_taiga2.png'),
               py.image.load('images\\tiles\\overworld\\taiga\\light_taiga3.png'),
               py.image.load('images\\tiles\\overworld\\taiga\\light_taiga4.png'),
               py.image.load('images\\tiles\\overworld\\taiga\\light_taiga5.png'),
               py.image.load('images\\tiles\\overworld\\taiga\\light_taiga6.png'),
               py.image.load('images\\tiles\\overworld\\taiga\\light_taiga7.png'),
               py.image.load('images\\tiles\\overworld\\taiga\\light_taiga8.png')]
DARK_TAIGA = [py.image.load('images\\tiles\\overworld\\taiga\\dark_taiga0.png'),
              py.image.load('images\\tiles\\overworld\\taiga\\dark_taiga1.png'),
              py.image.load('images\\tiles\\overworld\\taiga\\dark_taiga2.png'),
              py.image.load('images\\tiles\\overworld\\taiga\\dark_taiga3.png'),
              py.image.load('images\\tiles\\overworld\\taiga\\dark_taiga4.png'),
              py.image.load('images\\tiles\\overworld\\taiga\\dark_taiga5.png'),
              py.image.load('images\\tiles\\overworld\\taiga\\dark_taiga6.png'),
              py.image.load('images\\tiles\\overworld\\taiga\\dark_taiga7.png'),
              py.image.load('images\\tiles\\overworld\\taiga\\dark_taiga8.png')]
LIGHT_TEMPRAIN = [py.image.load('images\\tiles\\overworld\\temprain\\light_temprain0.png'),
                  py.image.load('images\\tiles\\overworld\\temprain\\light_temprain1.png'),
                  py.image.load('images\\tiles\\overworld\\temprain\\light_temprain2.png'),
                  py.image.load('images\\tiles\\overworld\\temprain\\light_temprain3.png'),
                  py.image.load('images\\tiles\\overworld\\temprain\\light_temprain4.png'),
                  py.image.load('images\\tiles\\overworld\\temprain\\light_temprain5.png'),
                  py.image.load('images\\tiles\\overworld\\temprain\\light_temprain6.png'),
                  py.image.load('images\\tiles\\overworld\\temprain\\light_temprain7.png'),
                  py.image.load('images\\tiles\\overworld\\temprain\\light_temprain8.png'), ]
DARK_TEMPRAIN = [py.image.load('images\\tiles\\overworld\\temprain\\dark_temprain0.png'),
                 py.image.load('images\\tiles\\overworld\\temprain\\dark_temprain1.png'),
                 py.image.load('images\\tiles\\overworld\\temprain\\dark_temprain2.png'),
                 py.image.load('images\\tiles\\overworld\\temprain\\dark_temprain3.png'),
                 py.image.load('images\\tiles\\overworld\\temprain\\dark_temprain4.png'),
                 py.image.load('images\\tiles\\overworld\\temprain\\dark_temprain5.png'),
                 py.image.load('images\\tiles\\overworld\\temprain\\dark_temprain6.png'),
                 py.image.load('images\\tiles\\overworld\\temprain\\dark_temprain7.png'),
                 py.image.load('images\\tiles\\overworld\\temprain\\dark_temprain8.png'), ]
LIGHT_TROPICRAIN = [py.image.load('images\\tiles\\overworld\\tropicrain\\light_tropicrain0.png'),
                    py.image.load('images\\tiles\\overworld\\tropicrain\\light_tropicrain1.png'),
                    py.image.load('images\\tiles\\overworld\\tropicrain\\light_tropicrain2.png'),
                    py.image.load('images\\tiles\\overworld\\tropicrain\\light_tropicrain3.png'),
                    py.image.load('images\\tiles\\overworld\\tropicrain\\light_tropicrain4.png'),
                    py.image.load('images\\tiles\\overworld\\tropicrain\\light_tropicrain5.png'),
                    py.image.load('images\\tiles\\overworld\\tropicrain\\light_tropicrain6.png'),
                    py.image.load('images\\tiles\\overworld\\tropicrain\\light_tropicrain7.png'),
                    py.image.load('images\\tiles\\overworld\\tropicrain\\light_tropicrain8.png'), ]
DARK_TROPICRAIN = [py.image.load('images\\tiles\\overworld\\tropicrain\\dark_tropicrain0.png'),
                   py.image.load('images\\tiles\\overworld\\tropicrain\\dark_tropicrain1.png'),
                   py.image.load('images\\tiles\\overworld\\tropicrain\\dark_tropicrain2.png'),
                   py.image.load('images\\tiles\\overworld\\tropicrain\\dark_tropicrain3.png'),
                   py.image.load('images\\tiles\\overworld\\tropicrain\\dark_tropicrain4.png'),
                   py.image.load('images\\tiles\\overworld\\tropicrain\\dark_tropicrain5.png'),
                   py.image.load('images\\tiles\\overworld\\tropicrain\\dark_tropicrain6.png'),
                   py.image.load('images\\tiles\\overworld\\tropicrain\\dark_tropicrain7.png'),
                   py.image.load('images\\tiles\\overworld\\tropicrain\\dark_tropicrain8.png'), ]
LIGHT_TUNDRA = [py.image.load('images\\tiles\\overworld\\tundra\\light_tundra0.png'),
                py.image.load('images\\tiles\\overworld\\tundra\\light_tundra1.png'),
                py.image.load('images\\tiles\\overworld\\tundra\\light_tundra2.png'),
                py.image.load('images\\tiles\\overworld\\tundra\\light_tundra3.png'),
                py.image.load('images\\tiles\\overworld\\tundra\\light_tundra4.png'),
                py.image.load('images\\tiles\\overworld\\tundra\\light_tundra5.png'),
                py.image.load('images\\tiles\\overworld\\tundra\\light_tundra6.png'),
                py.image.load('images\\tiles\\overworld\\tundra\\light_tundra7.png'),
                py.image.load('images\\tiles\\overworld\\tundra\\light_tundra8.png')]
DARK_TUNDRA = [py.image.load('images\\tiles\\overworld\\tundra\\dark_tundra0.png'),
               py.image.load('images\\tiles\\overworld\\tundra\\dark_tundra1.png'),
               py.image.load('images\\tiles\\overworld\\tundra\\dark_tundra2.png'),
               py.image.load('images\\tiles\\overworld\\tundra\\dark_tundra3.png'),
               py.image.load('images\\tiles\\overworld\\tundra\\dark_tundra4.png'),
               py.image.load('images\\tiles\\overworld\\tundra\\dark_tundra5.png'),
               py.image.load('images\\tiles\\overworld\\tundra\\dark_tundra6.png'),
               py.image.load('images\\tiles\\overworld\\tundra\\dark_tundra7.png'),
               py.image.load('images\\tiles\\overworld\\tundra\\dark_tundra8.png')]

BIOMES = {
    'light_deep': LIGHT_DEEP,
    'dark_deep': DARK_DEEP,
    'light_desert': LIGHT_DESERT,
    'dark_desert': DARK_DESERT,
    'light_forest': LIGHT_FOREST,
    'dark_forest': DARK_FOREST,
    'light_plains': LIGHT_PLAINS,
    'dark_plains': DARK_PLAINS,
    'light_savannah': LIGHT_SAVANNAH,
    'dark_savannah': DARK_SAVANNAH,
    'light_shallow': LIGHT_SHALLOW,
    'dark_shallow': DARK_SHALLOW,
    'light_snow': LIGHT_SNOW,
    'dark_snow': DARK_SNOW,
    'light_temprain': LIGHT_TEMPRAIN,
    'dark_temprain': DARK_TEMPRAIN,
    'light_tropicrain': LIGHT_TROPICRAIN,
    'dark_tropicrain': DARK_TROPICRAIN,
    'light_taiga': LIGHT_TAIGA,
    'dark_taiga': DARK_TAIGA,
    'light_tundra': LIGHT_TUNDRA,
    'dark_tundra': DARK_TUNDRA,
}

TILE_BASE = {
    'black': py.image.load('images\\tiles\\black.png'),
}

DARK_ROCK_WALL = py.image.load('images\\tiles\\dark_wall.png')
LIGHT_ROCK_WALL = py.image.load('images\\tiles\\light_wall.png')

LIGHT_GRASS = [py.image.load('images\\tiles\\grass\\light_grass00.png'),
               py.image.load('images\\tiles\\grass\\light_grass01.png'),
               py.image.load('images\\tiles\\grass\\light_grass02.png'),
               py.image.load('images\\tiles\\grass\\light_grass03.png'),
               py.image.load('images\\tiles\\grass\\light_grass04.png'),
               py.image.load('images\\tiles\\grass\\light_grass05.png'),
               py.image.load('images\\tiles\\grass\\light_grass06.png'),
               py.image.load('images\\tiles\\grass\\light_grass07.png'),
               py.image.load('images\\tiles\\grass\\light_grass08.png'),
               py.image.load('images\\tiles\\grass\\light_grass09.png'),
               py.image.load('images\\tiles\\grass\\light_grass10.png'),
               py.image.load('images\\tiles\\grass\\light_grass11.png'),
               py.image.load('images\\tiles\\grass\\light_grass12.png')]
DARK_GRASS = [py.image.load('images\\tiles\\grass\\dark_grass00.png'),
              py.image.load('images\\tiles\\grass\\dark_grass01.png'),
              py.image.load('images\\tiles\\grass\\dark_grass02.png'),
              py.image.load('images\\tiles\\grass\\dark_grass03.png'),
              py.image.load('images\\tiles\\grass\\dark_grass04.png'),
              py.image.load('images\\tiles\\grass\\dark_grass05.png'),
              py.image.load('images\\tiles\\grass\\dark_grass06.png'),
              py.image.load('images\\tiles\\grass\\dark_grass07.png'),
              py.image.load('images\\tiles\\grass\\dark_grass08.png'),
              py.image.load('images\\tiles\\grass\\dark_grass09.png'),
              py.image.load('images\\tiles\\grass\\dark_grass10.png'),
              py.image.load('images\\tiles\\grass\\dark_grass11.png'),
              py.image.load('images\\tiles\\grass\\dark_grass12.png')]
LIGHT_ROAD = {
    '00001011': FrozenSurface.load('images\\road\\', 'light_road00001011.png'),
    '00010110': FrozenSurface.load('images\\road\\', 'light_road00010110.png'),
    '00011111': FrozenSurface.load('images\\road\\', 'light_road00011111.png'),
    '01101000': FrozenSurface.load('images\\road\\', 'light_road01101000.png'),
    '01101011': FrozenSurface.load('images\\road\\', 'light_road01101011.png'),
    '01111111': FrozenSurface.load('images\\road\\', 'light_road01111111.png'),
    '11010000': FrozenSurface.load('images\\road\\', 'light_road11010000.png'),
    '11010110': FrozenSurface.load('images\\road\\', 'light_road11010110.png'),
    '11011011': FrozenSurface.load('images\\road\\', 'light_road11011011.png'),
    '11111000': FrozenSurface.load('images\\road\\', 'light_road11111000.png'),
    '11111110': FrozenSurface.load('images\\road\\', 'light_road11111110.png'),
    '11111111': FrozenSurface.load('images\\road\\', 'light_road11111111.png'),
}
DARK_ROAD = {
    '00001011': FrozenSurface.load('images\\road\\', 'dark_road00001011.png'),
    '00010110': FrozenSurface.load('images\\road\\', 'dark_road00010110.png'),
    '00011111': FrozenSurface.load('images\\road\\', 'dark_road00011111.png'),
    '01101000': FrozenSurface.load('images\\road\\', 'dark_road01101000.png'),
    '01101011': FrozenSurface.load('images\\road\\', 'dark_road01101011.png'),
    '01111111': FrozenSurface.load('images\\road\\', 'dark_road01111111.png'),
    '11010000': FrozenSurface.load('images\\road\\', 'dark_road11010000.png'),
    '11010110': FrozenSurface.load('images\\road\\', 'dark_road11010110.png'),
    '11011011': FrozenSurface.load('images\\road\\', 'dark_road11011011.png'),
    '11111000': FrozenSurface.load('images\\road\\', 'dark_road11111000.png'),
    '11111110': FrozenSurface.load('images\\road\\', 'dark_road11111110.png'),
    '11111111': FrozenSurface.load('images\\road\\', 'dark_road11111111.png'),
}
LIGHT_DIRT = [py.image.load('images\\tiles\\dirt\\light_dirt0.png'),
              py.image.load('images\\tiles\\dirt\\light_dirt1.png'),
              py.image.load('images\\tiles\\dirt\\light_dirt2.png'),
              py.image.load('images\\tiles\\dirt\\light_dirt3.png'),
              py.image.load('images\\tiles\\dirt\\light_dirt4.png'),
              py.image.load('images\\tiles\\dirt\\light_dirt5.png'),
              py.image.load('images\\tiles\\dirt\\light_dirt6.png'),
              py.image.load('images\\tiles\\dirt\\light_dirt7.png'),
              py.image.load('images\\tiles\\dirt\\light_dirt8.png')]
DARK_DIRT = [py.image.load('images\\tiles\\dirt\\dark_dirt0.png'),
             py.image.load('images\\tiles\\dirt\\dark_dirt1.png'),
             py.image.load('images\\tiles\\dirt\\dark_dirt2.png'),
             py.image.load('images\\tiles\\dirt\\dark_dirt3.png'),
             py.image.load('images\\tiles\\dirt\\dark_dirt4.png'),
             py.image.load('images\\tiles\\dirt\\dark_dirt5.png'),
             py.image.load('images\\tiles\\dirt\\dark_dirt6.png'),
             py.image.load('images\\tiles\\dirt\\dark_dirt7.png'),
             py.image.load('images\\tiles\\dirt\\dark_dirt8.png')]


WALL_TOP_H = FrozenSurface.load('images\\structures\\inn\\', 'wall_top_h.png')
WALL_TOP_V = FrozenSurface.load('images\\structures\\inn\\', 'wall_top_v.png')
WALL_MID = FrozenSurface.load('images\\structures\\inn\\', 'wall_mid.png')
WALL_BOT = FrozenSurface.load('images\\structures\\inn\\', 'wall_bot.png')
PILLAR_TOP = FrozenSurface.load('images\\structures\\inn\\', 'pillar_top.png')
PILLAR_MID = FrozenSurface.load('images\\structures\\inn\\', 'pillar_mid.png')
PILLAR_BOT = FrozenSurface.load('images\\structures\\inn\\', 'pillar_bot.png')
INN_FLOOR_S = FrozenSurface.load('images\\structures\\inn\\', 'inn_floor_s.png')

def get_hut_obj():
    # width 17, height 17
    pf = 'images\\structures\\hut\\'
    obj_lists = [[py.image.load(pf + 'light_hut000.png'), py.image.load(pf + 'light_hut001.png'),
                  py.image.load(pf + 'light_hut002.png'), py.image.load(pf + 'light_hut003.png'),
                  py.image.load(pf + 'light_hut004.png'), py.image.load(pf + 'light_hut005.png'),
                  py.image.load(pf + 'light_hut006.png'), py.image.load(pf + 'light_hut007.png'),
                  py.image.load(pf + 'light_hut008.png'), py.image.load(pf + 'light_hut009.png'),
                  py.image.load(pf + 'light_hut010.png'), py.image.load(pf + 'light_hut011.png'),
                  py.image.load(pf + 'light_hut012.png'), py.image.load(pf + 'light_hut013.png'),
                  py.image.load(pf + 'light_hut014.png'), py.image.load(pf + 'light_hut015.png'),
                  py.image.load(pf + 'light_hut016.png'), py.image.load(pf + 'light_hut017.png'),
                  py.image.load(pf + 'light_hut018.png'), py.image.load(pf + 'light_hut019.png'),
                  py.image.load(pf + 'light_hut020.png'), py.image.load(pf + 'light_hut021.png'),
                  py.image.load(pf + 'light_hut022.png'), py.image.load(pf + 'light_hut023.png'),
                  py.image.load(pf + 'light_hut024.png'), py.image.load(pf + 'light_hut025.png'),
                  py.image.load(pf + 'light_hut026.png'), py.image.load(pf + 'light_hut027.png'),
                  py.image.load(pf + 'light_hut028.png'), py.image.load(pf + 'light_hut029.png'),
                  py.image.load(pf + 'light_hut030.png'), py.image.load(pf + 'light_hut031.png'),
                  py.image.load(pf + 'light_hut032.png'), py.image.load(pf + 'light_hut033.png'),
                  py.image.load(pf + 'light_hut034.png'), py.image.load(pf + 'light_hut035.png'),
                  py.image.load(pf + 'light_hut036.png'), py.image.load(pf + 'light_hut037.png'),
                  py.image.load(pf + 'light_hut038.png'), py.image.load(pf + 'light_hut039.png'),
                  py.image.load(pf + 'light_hut040.png'), py.image.load(pf + 'light_hut041.png'),
                  py.image.load(pf + 'light_hut042.png'), py.image.load(pf + 'light_hut043.png'),
                  py.image.load(pf + 'light_hut044.png'), py.image.load(pf + 'light_hut045.png'),
                  py.image.load(pf + 'light_hut046.png'), py.image.load(pf + 'light_hut047.png'),
                  py.image.load(pf + 'light_hut048.png'), py.image.load(pf + 'light_hut049.png'),
                  py.image.load(pf + 'light_hut050.png'), py.image.load(pf + 'light_hut051.png'),
                  py.image.load(pf + 'light_hut052.png'), py.image.load(pf + 'light_hut053.png'),
                  py.image.load(pf + 'light_hut054.png'), py.image.load(pf + 'light_hut055.png'),
                  py.image.load(pf + 'light_hut056.png'), py.image.load(pf + 'light_hut057.png'),
                  py.image.load(pf + 'light_hut058.png'), py.image.load(pf + 'light_hut059.png'),
                  py.image.load(pf + 'light_hut060.png'), py.image.load(pf + 'light_hut061.png'),
                  py.image.load(pf + 'light_hut062.png'), py.image.load(pf + 'light_hut063.png'),
                  py.image.load(pf + 'light_hut064.png'), py.image.load(pf + 'light_hut065.png'),
                  py.image.load(pf + 'light_hut066.png'), py.image.load(pf + 'light_hut067.png'),
                  py.image.load(pf + 'light_hut068.png'), py.image.load(pf + 'light_hut069.png'),
                  py.image.load(pf + 'light_hut070.png'), py.image.load(pf + 'light_hut071.png'),
                  py.image.load(pf + 'light_hut072.png'), py.image.load(pf + 'light_hut073.png'),
                  py.image.load(pf + 'light_hut074.png'), py.image.load(pf + 'light_hut075.png'),
                  py.image.load(pf + 'light_hut076.png'), py.image.load(pf + 'light_hut077.png'),
                  py.image.load(pf + 'light_hut078.png'), py.image.load(pf + 'light_hut079.png'),
                  py.image.load(pf + 'light_hut080.png'), py.image.load(pf + 'light_hut081.png'),
                  py.image.load(pf + 'light_hut082.png'), py.image.load(pf + 'light_hut083.png'),
                  py.image.load(pf + 'light_hut084.png'), py.image.load(pf + 'light_hut085.png'),
                  py.image.load(pf + 'light_hut086.png'), py.image.load(pf + 'light_hut087.png'),
                  py.image.load(pf + 'light_hut088.png'), py.image.load(pf + 'light_hut089.png'),
                  py.image.load(pf + 'light_hut090.png'), py.image.load(pf + 'light_hut091.png'),
                  py.image.load(pf + 'light_hut092.png'), py.image.load(pf + 'light_hut093.png'),
                  py.image.load(pf + 'light_hut094.png'), py.image.load(pf + 'light_hut095.png'),
                  py.image.load(pf + 'light_hut096.png'), py.image.load(pf + 'light_hut097.png'),
                  py.image.load(pf + 'light_hut098.png'), py.image.load(pf + 'light_hut099.png'),
                  py.image.load(pf + 'light_hut100.png'), py.image.load(pf + 'light_hut101.png'),
                  py.image.load(pf + 'light_hut102.png'), py.image.load(pf + 'light_hut103.png'),
                  py.image.load(pf + 'light_hut104.png'), py.image.load(pf + 'light_hut105.png'),
                  py.image.load(pf + 'light_hut106.png'), py.image.load(pf + 'light_hut107.png'),
                  py.image.load(pf + 'light_hut108.png'), py.image.load(pf + 'light_hut109.png'),
                  py.image.load(pf + 'light_hut110.png'), py.image.load(pf + 'light_hut111.png'),
                  py.image.load(pf + 'light_hut112.png'), py.image.load(pf + 'light_hut113.png'),
                  py.image.load(pf + 'light_hut114.png'), py.image.load(pf + 'light_hut115.png'),
                  py.image.load(pf + 'light_hut116.png'), py.image.load(pf + 'light_hut117.png'),
                  py.image.load(pf + 'light_hut118.png'), py.image.load(pf + 'light_hut119.png'),
                  py.image.load(pf + 'light_hut120.png'), py.image.load(pf + 'light_hut121.png'),
                  py.image.load(pf + 'light_hut122.png'), py.image.load(pf + 'light_hut123.png'),
                  py.image.load(pf + 'light_hut124.png'), py.image.load(pf + 'light_hut125.png'),
                  py.image.load(pf + 'light_hut126.png'), py.image.load(pf + 'light_hut127.png'),
                  py.image.load(pf + 'light_hut128.png'), py.image.load(pf + 'light_hut129.png'),
                  py.image.load(pf + 'light_hut130.png'), py.image.load(pf + 'light_hut131.png'),
                  py.image.load(pf + 'light_hut132.png'), py.image.load(pf + 'light_hut133.png'),
                  py.image.load(pf + 'light_hut134.png'), py.image.load(pf + 'light_hut135.png'),
                  py.image.load(pf + 'light_hut136.png'), py.image.load(pf + 'light_hut137.png'),
                  py.image.load(pf + 'light_hut138.png'), py.image.load(pf + 'light_hut139.png'),
                  py.image.load(pf + 'light_hut140.png'), py.image.load(pf + 'light_hut141.png'),
                  py.image.load(pf + 'light_hut142.png'), py.image.load(pf + 'light_hut143.png'),
                  py.image.load(pf + 'light_hut144.png'), py.image.load(pf + 'light_hut145.png'),
                  py.image.load(pf + 'light_hut146.png'), py.image.load(pf + 'light_hut147.png'),
                  py.image.load(pf + 'light_hut148.png'), py.image.load(pf + 'light_hut149.png'),
                  py.image.load(pf + 'light_hut150.png'), py.image.load(pf + 'light_hut151.png'),
                  py.image.load(pf + 'light_hut152.png'), py.image.load(pf + 'light_hut153.png'),
                  py.image.load(pf + 'light_hut154.png'), py.image.load(pf + 'light_hut155.png'),
                  py.image.load(pf + 'light_hut156.png'), py.image.load(pf + 'light_hut157.png'),
                  py.image.load(pf + 'light_hut158.png'), py.image.load(pf + 'light_hut159.png'),
                  py.image.load(pf + 'light_hut160.png'), py.image.load(pf + 'light_hut161.png'),
                  py.image.load(pf + 'light_hut162.png'), py.image.load(pf + 'light_hut163.png'),
                  py.image.load(pf + 'light_hut164.png'), py.image.load(pf + 'light_hut165.png'),
                  py.image.load(pf + 'light_hut166.png'), py.image.load(pf + 'light_hut167.png'),
                  py.image.load(pf + 'light_hut168.png'), py.image.load(pf + 'light_hut169.png'),
                  py.image.load(pf + 'light_hut170.png'), py.image.load(pf + 'light_hut171.png'),
                  py.image.load(pf + 'light_hut172.png'), py.image.load(pf + 'light_hut173.png'),
                  py.image.load(pf + 'light_hut174.png'), py.image.load(pf + 'light_hut175.png'),
                  py.image.load(pf + 'light_hut176.png'), py.image.load(pf + 'light_hut177.png'),
                  py.image.load(pf + 'light_hut178.png'), py.image.load(pf + 'light_hut179.png'),
                  py.image.load(pf + 'light_hut180.png'), py.image.load(pf + 'light_hut181.png'),
                  py.image.load(pf + 'light_hut182.png'), py.image.load(pf + 'light_hut183.png'),
                  py.image.load(pf + 'light_hut184.png'), py.image.load(pf + 'light_hut185.png'),
                  py.image.load(pf + 'light_hut186.png'), py.image.load(pf + 'light_hut187.png'),
                  py.image.load(pf + 'light_hut188.png'), py.image.load(pf + 'light_hut189.png'),
                  py.image.load(pf + 'light_hut190.png'), py.image.load(pf + 'light_hut191.png'),
                  py.image.load(pf + 'light_hut192.png'), py.image.load(pf + 'light_hut193.png'),
                  py.image.load(pf + 'light_hut194.png'), py.image.load(pf + 'light_hut195.png'),
                  py.image.load(pf + 'light_hut196.png'), py.image.load(pf + 'light_hut197.png'),
                  py.image.load(pf + 'light_hut198.png'), py.image.load(pf + 'light_hut199.png'),
                  py.image.load(pf + 'light_hut200.png'), py.image.load(pf + 'light_hut201.png'),
                  py.image.load(pf + 'light_hut202.png'), py.image.load(pf + 'light_hut203.png'),
                  py.image.load(pf + 'light_hut204.png'), py.image.load(pf + 'light_hut205.png'),
                  py.image.load(pf + 'light_hut206.png'), py.image.load(pf + 'light_hut207.png'),
                  py.image.load(pf + 'light_hut208.png'), py.image.load(pf + 'light_hut209.png'),
                  py.image.load(pf + 'light_hut210.png'), py.image.load(pf + 'light_hut211.png'),
                  py.image.load(pf + 'light_hut212.png'), py.image.load(pf + 'light_hut213.png'),
                  py.image.load(pf + 'light_hut214.png'), py.image.load(pf + 'light_hut215.png'),
                  py.image.load(pf + 'light_hut216.png'), py.image.load(pf + 'light_hut217.png'),
                  py.image.load(pf + 'light_hut218.png'), py.image.load(pf + 'light_hut219.png'),
                  py.image.load(pf + 'light_hut220.png'), py.image.load(pf + 'light_hut221.png'),
                  py.image.load(pf + 'light_hut222.png'), py.image.load(pf + 'light_hut223.png'),
                  py.image.load(pf + 'light_hut224.png'), py.image.load(pf + 'light_hut225.png'),
                  py.image.load(pf + 'light_hut226.png'), py.image.load(pf + 'light_hut227.png'),
                  py.image.load(pf + 'light_hut228.png'), py.image.load(pf + 'light_hut229.png'),
                  py.image.load(pf + 'light_hut230.png'), py.image.load(pf + 'light_hut231.png'),
                  py.image.load(pf + 'light_hut232.png'), py.image.load(pf + 'light_hut233.png'),
                  py.image.load(pf + 'light_hut234.png'), py.image.load(pf + 'light_hut235.png'),
                  py.image.load(pf + 'light_hut236.png'), py.image.load(pf + 'light_hut237.png'),
                  py.image.load(pf + 'light_hut238.png'), py.image.load(pf + 'light_hut239.png'),
                  py.image.load(pf + 'light_hut240.png'), py.image.load(pf + 'light_hut241.png'),
                  py.image.load(pf + 'light_hut242.png'), py.image.load(pf + 'light_hut243.png'),
                  py.image.load(pf + 'light_hut244.png'), py.image.load(pf + 'light_hut245.png'),
                  py.image.load(pf + 'light_hut246.png'), py.image.load(pf + 'light_hut247.png'),
                  py.image.load(pf + 'light_hut248.png'), py.image.load(pf + 'light_hut249.png'),
                  py.image.load(pf + 'light_hut250.png'), py.image.load(pf + 'light_hut251.png'),
                  py.image.load(pf + 'light_hut252.png'), py.image.load(pf + 'light_hut253.png'),
                  py.image.load(pf + 'light_hut254.png'), py.image.load(pf + 'light_hut255.png'),
                  py.image.load(pf + 'light_hut256.png'), py.image.load(pf + 'light_hut257.png'),
                  py.image.load(pf + 'light_hut258.png'), py.image.load(pf + 'light_hut259.png'),
                  py.image.load(pf + 'light_hut260.png'), py.image.load(pf + 'light_hut261.png'),
                  py.image.load(pf + 'light_hut262.png'), py.image.load(pf + 'light_hut263.png'),
                  py.image.load(pf + 'light_hut264.png'), py.image.load(pf + 'light_hut265.png'),
                  py.image.load(pf + 'light_hut266.png'), py.image.load(pf + 'light_hut267.png'),
                  py.image.load(pf + 'light_hut268.png'), py.image.load(pf + 'light_hut269.png'),
                  py.image.load(pf + 'light_hut270.png'), py.image.load(pf + 'light_hut271.png'),
                  py.image.load(pf + 'light_hut272.png'), py.image.load(pf + 'light_hut273.png'),
                  py.image.load(pf + 'light_hut274.png'), py.image.load(pf + 'light_hut275.png'),
                  py.image.load(pf + 'light_hut276.png'), py.image.load(pf + 'light_hut277.png'),
                  py.image.load(pf + 'light_hut278.png'), py.image.load(pf + 'light_hut279.png'),
                  py.image.load(pf + 'light_hut280.png'), py.image.load(pf + 'light_hut281.png'),
                  py.image.load(pf + 'light_hut282.png'), py.image.load(pf + 'light_hut283.png'),
                  py.image.load(pf + 'light_hut284.png'), py.image.load(pf + 'light_hut285.png'),
                  py.image.load(pf + 'light_hut286.png'), py.image.load(pf + 'light_hut287.png'),
                  py.image.load(pf + 'light_hut288.png'),
                  ],
                 [py.image.load(pf + 'dark_hut000.png'), py.image.load(pf + 'dark_hut001.png'),
                  py.image.load(pf + 'dark_hut002.png'), py.image.load(pf + 'dark_hut003.png'),
                  py.image.load(pf + 'dark_hut004.png'), py.image.load(pf + 'dark_hut005.png'),
                  py.image.load(pf + 'dark_hut006.png'), py.image.load(pf + 'dark_hut007.png'),
                  py.image.load(pf + 'dark_hut008.png'), py.image.load(pf + 'dark_hut009.png'),
                  py.image.load(pf + 'dark_hut010.png'), py.image.load(pf + 'dark_hut011.png'),
                  py.image.load(pf + 'dark_hut012.png'), py.image.load(pf + 'dark_hut013.png'),
                  py.image.load(pf + 'dark_hut014.png'), py.image.load(pf + 'dark_hut015.png'),
                  py.image.load(pf + 'dark_hut016.png'), py.image.load(pf + 'dark_hut017.png'),
                  py.image.load(pf + 'dark_hut018.png'), py.image.load(pf + 'dark_hut019.png'),
                  py.image.load(pf + 'dark_hut020.png'), py.image.load(pf + 'dark_hut021.png'),
                  py.image.load(pf + 'dark_hut022.png'), py.image.load(pf + 'dark_hut023.png'),
                  py.image.load(pf + 'dark_hut024.png'), py.image.load(pf + 'dark_hut025.png'),
                  py.image.load(pf + 'dark_hut026.png'), py.image.load(pf + 'dark_hut027.png'),
                  py.image.load(pf + 'dark_hut028.png'), py.image.load(pf + 'dark_hut029.png'),
                  py.image.load(pf + 'dark_hut030.png'), py.image.load(pf + 'dark_hut031.png'),
                  py.image.load(pf + 'dark_hut032.png'), py.image.load(pf + 'dark_hut033.png'),
                  py.image.load(pf + 'dark_hut034.png'), py.image.load(pf + 'dark_hut035.png'),
                  py.image.load(pf + 'dark_hut036.png'), py.image.load(pf + 'dark_hut037.png'),
                  py.image.load(pf + 'dark_hut038.png'), py.image.load(pf + 'dark_hut039.png'),
                  py.image.load(pf + 'dark_hut040.png'), py.image.load(pf + 'dark_hut041.png'),
                  py.image.load(pf + 'dark_hut042.png'), py.image.load(pf + 'dark_hut043.png'),
                  py.image.load(pf + 'dark_hut044.png'), py.image.load(pf + 'dark_hut045.png'),
                  py.image.load(pf + 'dark_hut046.png'), py.image.load(pf + 'dark_hut047.png'),
                  py.image.load(pf + 'dark_hut048.png'), py.image.load(pf + 'dark_hut049.png'),
                  py.image.load(pf + 'dark_hut050.png'), py.image.load(pf + 'dark_hut051.png'),
                  py.image.load(pf + 'dark_hut052.png'), py.image.load(pf + 'dark_hut053.png'),
                  py.image.load(pf + 'dark_hut054.png'), py.image.load(pf + 'dark_hut055.png'),
                  py.image.load(pf + 'dark_hut056.png'), py.image.load(pf + 'dark_hut057.png'),
                  py.image.load(pf + 'dark_hut058.png'), py.image.load(pf + 'dark_hut059.png'),
                  py.image.load(pf + 'dark_hut060.png'), py.image.load(pf + 'dark_hut061.png'),
                  py.image.load(pf + 'dark_hut062.png'), py.image.load(pf + 'dark_hut063.png'),
                  py.image.load(pf + 'dark_hut064.png'), py.image.load(pf + 'dark_hut065.png'),
                  py.image.load(pf + 'dark_hut066.png'), py.image.load(pf + 'dark_hut067.png'),
                  py.image.load(pf + 'dark_hut068.png'), py.image.load(pf + 'dark_hut069.png'),
                  py.image.load(pf + 'dark_hut070.png'), py.image.load(pf + 'dark_hut071.png'),
                  py.image.load(pf + 'dark_hut072.png'), py.image.load(pf + 'dark_hut073.png'),
                  py.image.load(pf + 'dark_hut074.png'), py.image.load(pf + 'dark_hut075.png'),
                  py.image.load(pf + 'dark_hut076.png'), py.image.load(pf + 'dark_hut077.png'),
                  py.image.load(pf + 'dark_hut078.png'), py.image.load(pf + 'dark_hut079.png'),
                  py.image.load(pf + 'dark_hut080.png'), py.image.load(pf + 'dark_hut081.png'),
                  py.image.load(pf + 'dark_hut082.png'), py.image.load(pf + 'dark_hut083.png'),
                  py.image.load(pf + 'dark_hut084.png'), py.image.load(pf + 'dark_hut085.png'),
                  py.image.load(pf + 'dark_hut086.png'), py.image.load(pf + 'dark_hut087.png'),
                  py.image.load(pf + 'dark_hut088.png'), py.image.load(pf + 'dark_hut089.png'),
                  py.image.load(pf + 'dark_hut090.png'), py.image.load(pf + 'dark_hut091.png'),
                  py.image.load(pf + 'dark_hut092.png'), py.image.load(pf + 'dark_hut093.png'),
                  py.image.load(pf + 'dark_hut094.png'), py.image.load(pf + 'dark_hut095.png'),
                  py.image.load(pf + 'dark_hut096.png'), py.image.load(pf + 'dark_hut097.png'),
                  py.image.load(pf + 'dark_hut098.png'), py.image.load(pf + 'dark_hut099.png'),
                  py.image.load(pf + 'dark_hut100.png'), py.image.load(pf + 'dark_hut101.png'),
                  py.image.load(pf + 'dark_hut102.png'), py.image.load(pf + 'dark_hut103.png'),
                  py.image.load(pf + 'dark_hut104.png'), py.image.load(pf + 'dark_hut105.png'),
                  py.image.load(pf + 'dark_hut106.png'), py.image.load(pf + 'dark_hut107.png'),
                  py.image.load(pf + 'dark_hut108.png'), py.image.load(pf + 'dark_hut109.png'),
                  py.image.load(pf + 'dark_hut110.png'), py.image.load(pf + 'dark_hut111.png'),
                  py.image.load(pf + 'dark_hut112.png'), py.image.load(pf + 'dark_hut113.png'),
                  py.image.load(pf + 'dark_hut114.png'), py.image.load(pf + 'dark_hut115.png'),
                  py.image.load(pf + 'dark_hut116.png'), py.image.load(pf + 'dark_hut117.png'),
                  py.image.load(pf + 'dark_hut118.png'), py.image.load(pf + 'dark_hut119.png'),
                  py.image.load(pf + 'dark_hut120.png'), py.image.load(pf + 'dark_hut121.png'),
                  py.image.load(pf + 'dark_hut122.png'), py.image.load(pf + 'dark_hut123.png'),
                  py.image.load(pf + 'dark_hut124.png'), py.image.load(pf + 'dark_hut125.png'),
                  py.image.load(pf + 'dark_hut126.png'), py.image.load(pf + 'dark_hut127.png'),
                  py.image.load(pf + 'dark_hut128.png'), py.image.load(pf + 'dark_hut129.png'),
                  py.image.load(pf + 'dark_hut130.png'), py.image.load(pf + 'dark_hut131.png'),
                  py.image.load(pf + 'dark_hut132.png'), py.image.load(pf + 'dark_hut133.png'),
                  py.image.load(pf + 'dark_hut134.png'), py.image.load(pf + 'dark_hut135.png'),
                  py.image.load(pf + 'dark_hut136.png'), py.image.load(pf + 'dark_hut137.png'),
                  py.image.load(pf + 'dark_hut138.png'), py.image.load(pf + 'dark_hut139.png'),
                  py.image.load(pf + 'dark_hut140.png'), py.image.load(pf + 'dark_hut141.png'),
                  py.image.load(pf + 'dark_hut142.png'), py.image.load(pf + 'dark_hut143.png'),
                  py.image.load(pf + 'dark_hut144.png'), py.image.load(pf + 'dark_hut145.png'),
                  py.image.load(pf + 'dark_hut146.png'), py.image.load(pf + 'dark_hut147.png'),
                  py.image.load(pf + 'dark_hut148.png'), py.image.load(pf + 'dark_hut149.png'),
                  py.image.load(pf + 'dark_hut150.png'), py.image.load(pf + 'dark_hut151.png'),
                  py.image.load(pf + 'dark_hut152.png'), py.image.load(pf + 'dark_hut153.png'),
                  py.image.load(pf + 'dark_hut154.png'), py.image.load(pf + 'dark_hut155.png'),
                  py.image.load(pf + 'dark_hut156.png'), py.image.load(pf + 'dark_hut157.png'),
                  py.image.load(pf + 'dark_hut158.png'), py.image.load(pf + 'dark_hut159.png'),
                  py.image.load(pf + 'dark_hut160.png'), py.image.load(pf + 'dark_hut161.png'),
                  py.image.load(pf + 'dark_hut162.png'), py.image.load(pf + 'dark_hut163.png'),
                  py.image.load(pf + 'dark_hut164.png'), py.image.load(pf + 'dark_hut165.png'),
                  py.image.load(pf + 'dark_hut166.png'), py.image.load(pf + 'dark_hut167.png'),
                  py.image.load(pf + 'dark_hut168.png'), py.image.load(pf + 'dark_hut169.png'),
                  py.image.load(pf + 'dark_hut170.png'), py.image.load(pf + 'dark_hut171.png'),
                  py.image.load(pf + 'dark_hut172.png'), py.image.load(pf + 'dark_hut173.png'),
                  py.image.load(pf + 'dark_hut174.png'), py.image.load(pf + 'dark_hut175.png'),
                  py.image.load(pf + 'dark_hut176.png'), py.image.load(pf + 'dark_hut177.png'),
                  py.image.load(pf + 'dark_hut178.png'), py.image.load(pf + 'dark_hut179.png'),
                  py.image.load(pf + 'dark_hut180.png'), py.image.load(pf + 'dark_hut181.png'),
                  py.image.load(pf + 'dark_hut182.png'), py.image.load(pf + 'dark_hut183.png'),
                  py.image.load(pf + 'dark_hut184.png'), py.image.load(pf + 'dark_hut185.png'),
                  py.image.load(pf + 'dark_hut186.png'), py.image.load(pf + 'dark_hut187.png'),
                  py.image.load(pf + 'dark_hut188.png'), py.image.load(pf + 'dark_hut189.png'),
                  py.image.load(pf + 'dark_hut190.png'), py.image.load(pf + 'dark_hut191.png'),
                  py.image.load(pf + 'dark_hut192.png'), py.image.load(pf + 'dark_hut193.png'),
                  py.image.load(pf + 'dark_hut194.png'), py.image.load(pf + 'dark_hut195.png'),
                  py.image.load(pf + 'dark_hut196.png'), py.image.load(pf + 'dark_hut197.png'),
                  py.image.load(pf + 'dark_hut198.png'), py.image.load(pf + 'dark_hut199.png'),
                  py.image.load(pf + 'dark_hut200.png'), py.image.load(pf + 'dark_hut201.png'),
                  py.image.load(pf + 'dark_hut202.png'), py.image.load(pf + 'dark_hut203.png'),
                  py.image.load(pf + 'dark_hut204.png'), py.image.load(pf + 'dark_hut205.png'),
                  py.image.load(pf + 'dark_hut206.png'), py.image.load(pf + 'dark_hut207.png'),
                  py.image.load(pf + 'dark_hut208.png'), py.image.load(pf + 'dark_hut209.png'),
                  py.image.load(pf + 'dark_hut210.png'), py.image.load(pf + 'dark_hut211.png'),
                  py.image.load(pf + 'dark_hut212.png'), py.image.load(pf + 'dark_hut213.png'),
                  py.image.load(pf + 'dark_hut214.png'), py.image.load(pf + 'dark_hut215.png'),
                  py.image.load(pf + 'dark_hut216.png'), py.image.load(pf + 'dark_hut217.png'),
                  py.image.load(pf + 'dark_hut218.png'), py.image.load(pf + 'dark_hut219.png'),
                  py.image.load(pf + 'dark_hut220.png'), py.image.load(pf + 'dark_hut221.png'),
                  py.image.load(pf + 'dark_hut222.png'), py.image.load(pf + 'dark_hut223.png'),
                  py.image.load(pf + 'dark_hut224.png'), py.image.load(pf + 'dark_hut225.png'),
                  py.image.load(pf + 'dark_hut226.png'), py.image.load(pf + 'dark_hut227.png'),
                  py.image.load(pf + 'dark_hut228.png'), py.image.load(pf + 'dark_hut229.png'),
                  py.image.load(pf + 'dark_hut230.png'), py.image.load(pf + 'dark_hut231.png'),
                  py.image.load(pf + 'dark_hut232.png'), py.image.load(pf + 'dark_hut233.png'),
                  py.image.load(pf + 'dark_hut234.png'), py.image.load(pf + 'dark_hut235.png'),
                  py.image.load(pf + 'dark_hut236.png'), py.image.load(pf + 'dark_hut237.png'),
                  py.image.load(pf + 'dark_hut238.png'), py.image.load(pf + 'dark_hut239.png'),
                  py.image.load(pf + 'dark_hut240.png'), py.image.load(pf + 'dark_hut241.png'),
                  py.image.load(pf + 'dark_hut242.png'), py.image.load(pf + 'dark_hut243.png'),
                  py.image.load(pf + 'dark_hut244.png'), py.image.load(pf + 'dark_hut245.png'),
                  py.image.load(pf + 'dark_hut246.png'), py.image.load(pf + 'dark_hut247.png'),
                  py.image.load(pf + 'dark_hut248.png'), py.image.load(pf + 'dark_hut249.png'),
                  py.image.load(pf + 'dark_hut250.png'), py.image.load(pf + 'dark_hut251.png'),
                  py.image.load(pf + 'dark_hut252.png'), py.image.load(pf + 'dark_hut253.png'),
                  py.image.load(pf + 'dark_hut254.png'), py.image.load(pf + 'dark_hut255.png'),
                  py.image.load(pf + 'dark_hut256.png'), py.image.load(pf + 'dark_hut257.png'),
                  py.image.load(pf + 'dark_hut258.png'), py.image.load(pf + 'dark_hut259.png'),
                  py.image.load(pf + 'dark_hut260.png'), py.image.load(pf + 'dark_hut261.png'),
                  py.image.load(pf + 'dark_hut262.png'), py.image.load(pf + 'dark_hut263.png'),
                  py.image.load(pf + 'dark_hut264.png'), py.image.load(pf + 'dark_hut265.png'),
                  py.image.load(pf + 'dark_hut266.png'), py.image.load(pf + 'dark_hut267.png'),
                  py.image.load(pf + 'dark_hut268.png'), py.image.load(pf + 'dark_hut269.png'),
                  py.image.load(pf + 'dark_hut270.png'), py.image.load(pf + 'dark_hut271.png'),
                  py.image.load(pf + 'dark_hut272.png'), py.image.load(pf + 'dark_hut273.png'),
                  py.image.load(pf + 'dark_hut274.png'), py.image.load(pf + 'dark_hut275.png'),
                  py.image.load(pf + 'dark_hut276.png'), py.image.load(pf + 'dark_hut277.png'),
                  py.image.load(pf + 'dark_hut278.png'), py.image.load(pf + 'dark_hut279.png'),
                  py.image.load(pf + 'dark_hut280.png'), py.image.load(pf + 'dark_hut281.png'),
                  py.image.load(pf + 'dark_hut282.png'), py.image.load(pf + 'dark_hut283.png'),
                  py.image.load(pf + 'dark_hut284.png'), py.image.load(pf + 'dark_hut285.png'),
                  py.image.load(pf + 'dark_hut286.png'), py.image.load(pf + 'dark_hut287.png'),
                  py.image.load(pf + 'dark_hut288.png'),
                  ]
                 ]

    return obj_lists


def get_house_images():
    # width = 5, height = 6
    pf = 'images\\structures\\house\\'
    obj_lists = [[py.image.load('images\\alpha.png'), py.image.load(pf + 'house00.png'),
                  py.image.load(pf + 'house01.png'), py.image.load(pf + 'house02.png'),
                  py.image.load('images\\alpha.png'), py.image.load(pf + 'house03.png'),
                  py.image.load(pf + 'house04.png'), py.image.load(pf + 'house05.png'),
                  py.image.load(pf + 'house06.png'), py.image.load(pf + 'house07.png'),
                  py.image.load(pf + 'house08.png'), py.image.load(pf + 'house09.png'),
                  py.image.load(pf + 'house10.png'), py.image.load(pf + 'house11.png'),
                  py.image.load(pf + 'house12.png'), py.image.load(pf + 'house13.png'),
                  py.image.load(pf + 'house14.png'), py.image.load(pf + 'house15.png'),
                  py.image.load(pf + 'house16.png'), py.image.load(pf + 'house17.png'),
                  py.image.load(pf + 'house18.png'), py.image.load(pf + 'house19.png'),
                  py.image.load(pf + 'house20.png'), py.image.load(pf + 'house21.png'),
                  py.image.load(pf + 'house22.png'), py.image.load(pf + 'house23.png'),
                  py.image.load(pf + 'house24.png'), py.image.load(pf + 'house25.png'),
                  py.image.load(pf + 'house26.png'), py.image.load(pf + 'house27.png')],
                 [py.image.load('images\\alpha.png'), py.image.load(pf + 'dark_house00.png'),
                  py.image.load(pf + 'dark_house01.png'), py.image.load(pf + 'dark_house02.png'),
                  py.image.load('images\\alpha.png'), py.image.load(pf + 'dark_house03.png'),
                  py.image.load(pf + 'dark_house04.png'), py.image.load(pf + 'dark_house05.png'),
                  py.image.load(pf + 'dark_house06.png'), py.image.load(pf + 'dark_house07.png'),
                  py.image.load(pf + 'dark_house08.png'), py.image.load(pf + 'dark_house09.png'),
                  py.image.load(pf + 'dark_house10.png'), py.image.load(pf + 'dark_house11.png'),
                  py.image.load(pf + 'dark_house12.png'), py.image.load(pf + 'dark_house13.png'),
                  py.image.load(pf + 'dark_house14.png'), py.image.load(pf + 'dark_house15.png'),
                  py.image.load(pf + 'dark_house16.png'), py.image.load(pf + 'dark_house17.png'),
                  py.image.load(pf + 'dark_house18.png'), py.image.load(pf + 'dark_house19.png'),
                  py.image.load(pf + 'dark_house20.png'), py.image.load(pf + 'dark_house21.png'),
                  py.image.load(pf + 'dark_house22.png'), py.image.load(pf + 'dark_house23.png'),
                  py.image.load(pf + 'dark_house24.png'), py.image.load(pf + 'dark_house25.png'),
                  py.image.load(pf + 'dark_house26.png'), py.image.load(pf + 'dark_house27.png')]
                 ]

    return obj_lists


OVERWORLD_TOWN = [[[FrozenSurface.load('images\\structures\\town\\', 'light_town00.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town01.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town02.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town03.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town04.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town05.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town06.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town07.png')],
                   [FrozenSurface.load('images\\structures\\town\\', 'light_town08.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town09.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town10.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town11.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town12.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town13.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town14.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town15.png')],
                   [FrozenSurface.load('images\\structures\\town\\', 'light_town16.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town17.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town18.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town19.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town20.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town21.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town22.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town23.png')],
                   [FrozenSurface.load('images\\structures\\town\\', 'light_town24.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town25.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town26.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town27.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town28.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town29.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town30.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'light_town31.png')]],
                  [[FrozenSurface.load('images\\structures\\town\\', 'dark_town00.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town01.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town02.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town03.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town04.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town05.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town06.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town07.png')],
                   [FrozenSurface.load('images\\structures\\town\\', 'dark_town08.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town09.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town10.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town11.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town12.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town13.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town14.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town15.png')],
                   [FrozenSurface.load('images\\structures\\town\\', 'dark_town16.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town17.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town18.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town19.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town20.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town21.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town22.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town23.png')],
                   [FrozenSurface.load('images\\structures\\town\\', 'dark_town24.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town25.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town26.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town27.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town28.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town29.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town30.png'),
                    FrozenSurface.load('images\\structures\\town\\', 'dark_town31.png')]]]


